
version: '3.8'

networks:
  JeffInternalLan:
    driver: bridge
    name: JeffInternalLan  # Create the network here first

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001
    networks:
      - JeffInternalLan
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      # Persist SQLite database
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Add Jeff-AI connection
      - JEFF_AI_URL=http://jeff-ai:8000
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s  # Give more time for dependencies
    networks:
      - JeffInternalLan
    restart: unless-stopped

  # Optional: Add a reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - JeffInternalLan
